version: '3'
services:

  odfe-node1:
    image: skysbsb/elastisearch-opendistro-plugins:7.8.0
    container_name: odfe-node1
    environment:
      - cluster.name=odfe-cluster
      - node.name=odfe-node1
      - discovery.seed_hosts=odfe-node1
      - cluster.initial_master_nodes=odfe-node1
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the Elasticsearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - odfe-data1:/usr/share/elasticsearch/data
      - ./config.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/config.yml
      - ./internal_users.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml
      - ./roles_mapping.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/roles_mapping.yml
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - odfe-net
      
  odfe-kibana:
    image: skysbsb/kibana-opendistro-plugins:7.8.0
    container_name: odfe-kibana
    depends_on:
      - odfe-node1
    ports:
      - 5601:5601    
    environment:
      - ELASTICSEARCH_HOSTS=["https://odfe-node1:9200"]
      # to rodando como admin por conta que o kibana ficava tentando
      # criar os indices do APM.. e tb pra teste, tanto faz..
      - ELASTICSEARCH_USERNAME=admin
      - ELASTICSEARCH_PASSWORD=admin
      # - ELASTICSEARCH_USERNAME=kibanaserver
      # - ELASTICSEARCH_PASSWORD=kibanaserver
      - ELASTICSEARCH_SSL_VERIFICATIONMODE=none
      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_KEY=/usr/share/kibana/config/kb-key.pem
      - SERVER_SSL_CERTIFICATE=/usr/share/kibana/config/kb.pem
      - XPACK_SECURITY_ENABLED=false
      # ELASTICSEARCH_USERNAME: kibana_system
      # ELASTICSEARCH_PASSWORD: CHANGEME
      # ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES: $CERTS_DIR/ca/ca.crt
      # SERVER_SSL_ENABLED: "true"
      # SERVER_SSL_KEY: $CERTS_DIR/kib01/kib01.key
      # SERVER_SSL_CERTIFICATE: $CERTS_DIR/kib01/kib01.crt
    volumes: 
      # - certs:$CERTS_DIR
      - ./kb.pem:/usr/share/kibana/config/kb.pem
      - ./kb-key.pem:/usr/share/kibana/config/kb-key.pem
    networks:
      - odfe-net   

  openldap:
    image: osixia/openldap:1.3.0
    container_name: openldap
    command: --copy-service # seemingly required to load directory.ldif
    ports:
      - 389:389
      - 636:636
    environment:
      - LDAP_ADMIN_PASSWORD=changethis
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_PASSWORD=changethistoo
    volumes:
      - ./directory.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/directory.ldif
    networks:
      - odfe-net

  openldap-admin:
    image: osixia/phpldapadmin:0.9.0
    container_name: openldap-admin
    ports:
      - 6443:443
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
    networks:
      - odfe-net

volumes:
  odfe-data1:
  odfe-data2:

networks:
  odfe-net:
